esphome:
  name: bedroom_sensor_pir
  platform: ESP8266
  board: d1_mini

substitutions:
  mqtt_topic_prefix: 'bedroom_sensor_pir'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: true
  # power_save_mode: LIGHT

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom PIR Fallback Hotspot"
    password: "5HfgEQHF9Dg4"

captive_portal:

# Enable logging
logger:
  level: info

status_led:
  pin:
    number: GPIO2
    inverted: True

sensor:
  - platform: wifi_signal
    name: "Bedroom PIR WiFi Signal"
    update_interval: 900s

binary_sensor:
  - platform: gpio
    pin: D4
    name: "Bedroom PIR"
    device_class: motion

# Enable Home Assistant API
api:

# web_server:
#   port: 80

ota:
  id: bedroom_sensor_pir_ota
  password: !secret ota_pwd

mqtt:
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_broker_username
  password: !secret mqtt_broker_pwd
  discovery: false
  birth_message:
    topic: $mqtt_topic_prefix/birth
    payload: online
  will_message:
    topic: $mqtt_topic_prefix/LWT
    payload: offline