esphome:
  name: ttgocamera
  platform: ESP32
  board: esp32dev

substitutions:
  mqtt_topic_prefix: 'bedroom_sensor_bme280'
  widget_title: "crsantos"
  font_name_bold: 'RobotoMono-Bold.ttf'
  font_name: 'RobotoMono-Regular.ttf'
  top_line_yy: "35"
  bottom_line_yy: "40"
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: true
  power_save_mode: HIGH

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ttgocamera Fallback Hotspot"
    password: "Pk4LATSBubej"

captive_portal:

# Enable logging
logger:
  level: info

# status_led:
#   pin:
#     number: GPIO2
#     inverted: yes
