esphome:
  name: bedroom_sensor_bme280
  platform: ESP8266
  board: d1_mini
  # on_boot:
  #   priority: -10
  #   then:
  #     - delay: 44s # Avoids sleeping on Clock page - showing an outdated time
  #     - component.update: ssd1306
  #     - display.page.show: page1

substitutions:
  mqtt_topic_prefix: 'bedroom_sensor_bme280'
  widget_title: "crsantos"
  font_name_bold: 'RobotoMono-Bold.ttf'
  font_name: 'RobotoMono-Regular.ttf'
  top_line_yy: "35"
  bottom_line_yy: "40"
  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: true
  power_save_mode: HIGH

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bme280 Fallback Hotspot"
    password: "5HfgEQHF9Dg4"

captive_portal:

# Enable logging
logger:
  level: info

# status_led:
#   pin:
#     number: GPIO2
#     inverted: yes

i2c:
  - id: bus_bme280
    sda: D2 # or GPIO4
    scl: D1 # or GPIO5
    scan: true

sensor:
  - platform: bme280
    i2c_id: bus_bme280
    temperature:
      name: temperature
      id: temperature
      oversampling: 1x
      filters:
        - or:
          - heartbeat: 900s
          - delta: 0.25
    pressure:
      name: pressure
      id: pressure
      oversampling: 1x
      filters:
        - or:
          - heartbeat: 900s
          - delta: 0.35
    humidity:
      name: humidity
      id: humidity
      oversampling: 1x
      filters:
        - or:
          - heartbeat: 900s
          - delta: 0.25
    address: 0x76
    update_interval: 30s
  - platform: wifi_signal
    name: 'wifi_signal'
    id: wifi_sensor
    update_interval: 900s
    availability:
      topic: '$mqtt_topic_prefix/status'
      payload_available: 'online'
      payload_not_available: 'offline'

interval:
  - interval: 10s
    then:
      - display.page.show_next: ssd1306
      - component.update: ssd1306
time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Lisbon"

display:
  - platform: ssd1306_i2c
    i2c_id: bus_bme280
    model: "SSD1306 128x64"
    reset_pin: D0
    id: ssd1306
    address: 0x3C
    pages:
      - id: page1
        lambda: |-

          // - Header
          it.printf(64, 0, id(font_roboto_small), TextAlign::TOP_CENTER, "$widget_title");
          
          // - Top
          // 0,top_line_yy
          if (id(temperature).has_state()) {
            it.printf(0, $top_line_yy, id(font_roboto_big), TextAlign::BASELINE_LEFT, "%.1f°", id(temperature).state);
          }

          // 127,top_line_yy
          if (id(humidity).has_state()) {
            it.printf(127, $top_line_yy, id(font_roboto_big), TextAlign::BASELINE_RIGHT , "%.1f%%", id(humidity).state);
          }

          // - Bottom

          // 0,bottom_line_yy
          if (id(wifi_sensor).has_state()) {
            it.printf(0, $bottom_line_yy, id(font_roboto_big), TextAlign::TOP_LEFT, "%.0f", id(wifi_sensor).state);
          }
          
          // 127,bottom_line_yy
          if (id(pressure).has_state()) {
            it.printf(127, $bottom_line_yy, id(font_roboto_big), TextAlign::TOP_RIGHT , "%.1fhP", id(pressure).state);
          }

      - id: page2
        lambda: |-
          it.printf(64, 0, id(font_roboto_small), TextAlign::TOP_CENTER, "$widget_title");
          it.strftime(64, 38, id(font_roboto_huge), TextAlign::CENTER, "%H:%M", id(sntp_time).now());

      - id: page3
        lambda: |-
          // Turn the whole display off.
          it.fill(COLOR_OFF);

font:
  - file: $font_name_bold
    id: font_roboto_small
    size: 12
  - file: $font_name
    id: font_roboto_big
    size: 18
  - file: $font_name
    id: font_roboto_huge
    size: 36

# deep_sleep:
#   id: deep_sleep_bedroom_sensor_bme280
#   run_duration: 45s
#   sleep_duration: 1min

# Enable Home Assistant API
api:

# web_server:
#   port: 80

ota:
  id: bedroom_sensor_bme280_ota
  password: !secret ota_pwd

mqtt:
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_broker_username
  password: !secret mqtt_broker_pwd
  discovery: false
  birth_message:
    topic: $mqtt_topic_prefix/birth
    payload: online
  will_message:
    topic: $mqtt_topic_prefix/LWT
    payload: offline
  # on_message:
  #   topic: $mqtt_topic_prefix/ota_mode
  #   payload: 'ON'
  #   then:
  #     - deep_sleep.prevent: deep_sleep_bedroom_sensor_bme280
