esphome:
  name: bedroom_sensor_bme280
  platform: ESP8266
  board: d1_mini

substitutions:
  mqtt_topic_prefix: 'bedroom_sensor_bme280'
  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: true
  # power_save_mode: HIGH

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bme280 Fallback Hotspot"
    password: "5HfgEQHF9Dg4"

captive_portal:

# Enable logging
logger:
  level: debug

status_led:
  pin:
    number: GPIO2
    inverted: yes

i2c:
  - id: bus_bme280
    sda: D2 # or GPIO4
    scl: D1 # or GPIO5
    scan: true

sensor:
  - platform: bme280
    i2c_id: bus_bme280
    temperature:
      name: temperature
      oversampling: 1x
      filters:
        - or:
          - heartbeat: 900s
          - delta: 0.25
    pressure:
      name: pressure
      oversampling: 1x
      filters:
        - or:
          - heartbeat: 900s
          - delta: 0.35
    humidity:
      name: humidity
      oversampling: 1x
      filters:
        - or:
          - heartbeat: 900s
          - delta: 0.25
    address: 0x76
    update_interval: 30s
  - platform: wifi_signal
    name: 'wifi_signal'
    update_interval: 900s
    availability:
      topic: '$mqtt_topic_prefix/status'
      payload_available: 'online'
      payload_not_available: 'offline'

deep_sleep:
  id: deep_sleep_bedroom_sensor_bme280
  run_duration: 30s
  sleep_duration: 5min

# Enable Home Assistant API
api:

# web_server:
#   port: 80

ota:
  id: bedroom_sensor_bme280_ota
  password: !secret ota_pwd

mqtt:
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_broker_username
  password: !secret mqtt_broker_pwd
  discovery: false
  birth_message:
    topic: $mqtt_topic_prefix/birth
    payload: online
  will_message:
    topic: $mqtt_topic_prefix/LWT
    payload: offline
  on_message:
    topic: $mqtt_topic_prefix/ota_mode
    payload: 'ON'
    then:
      - deep_sleep.prevent: deep_sleep_bedroom_sensor_bme280
