esphome:
  name: ultrasonic-hcsr04

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: DEBUG
  logs:
    mqtt.component: DEBUG
    mqtt.client: DEBUG

# Enable Home Assistant API
api:
  password: !secret wifi_pwd

ota:
  - platform: esphome
    password: !secret wifi_pwd

wifi:
  ssid: !secret wifi_ssid2
  password: !secret wifi_pwd
  use_address: "$devicename.local"
  fast_connect: true
  power_save_mode: HIGH

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ultrasonic Hcsr04"
    password: !secret wifi_pwd

captive_portal:

mqtt:
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_broker_username
  password: !secret mqtt_broker_pwd
  discovery: false
  birth_message:
    topic: $mqtt_topic_prefix/birth
    payload: online
  will_message:
    topic: $mqtt_topic_prefix/LWT
    payload: offline


sensor:
  - platform: ultrasonic
    trigger_pin: GPIO05
    echo_pin: GPIO04
    name: "Proteu Ultrasonic Sensor"
    update_interval: 3s
    timeout: 4m
    force_update: false
    filters:
      - lambda: if (isnan(x)) { return 999.0; } return x;
      - sliding_window_moving_average:
          window_size: 3
          send_every: 3