esphome:
  name: nfc_reader
  platform: ESP8266
  board: d1_mini

substitutions:
  devicename: "nfc_reader"
  mqtt_topic_prefix: 'nfc_reader'

mqtt:
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_broker_username
  password: !secret mqtt_broker_pwd
  discovery: false
  birth_message:
    topic: $mqtt_topic_prefix/birth
    payload: online
  will_message:
    topic: $mqtt_topic_prefix/LWT
    payload: offline

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  use_address: "$devicename.local"
  fast_connect: true
  power_save_mode: HIGH

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename Fallback Hotspot"
    password: "Pk4LATSBubej"

captive_portal:

# Enable logging
logger:
  level: VERY_VERBOSE

# status_led:
#   pin:
#     number: GPIO2
#     inverted: yes

api:

spi:
  clk_pin: D0
  miso_pin: D1
  mosi_pin: D2

pn532:
  cs_pin: D3
  update_interval: 1s
  on_tag:
    then:
      - mqtt.publish:
          topic: pn532/tag
          payload: !lambda 'return x;'

binary_sensor:
  - platform: pn532
    uid: 74-10-37-94
    name: "PN532 NFC Tag"